#!/bin/bash
APP_ROOT=`pwd`
VER=5.1.72
sudo apt-get install libncurses5-dev
rm -rf mysql-$VER
rm -rf mysql-install
mkdir mysql-install
if [ ! -f mysql-$VER.tar.gz ]; then
wget http://downloads.mysql.com/archives/get/file/mysql-$VER.tar.gz
fi
tar xzvf mysql-$VER.tar.gz
cd mysql-$VER
./configure --prefix=$APP_ROOT/mysql-install
make -j `nproc`
make install
cd ..
sed -e "s/3306/7000/g" ./mysql-install/share/mysql/my-large.cnf > ./my.cnf
./mysql-install/bin/mysql_install_db --defaults-file=./my.cnf

