#!/bin/bash
video_src = https://cinelerra-cv.org/footage/wide-20040607-small.avi
sudo apt-get install mencoder libsqlite3-dev
sudo apt-get install libexpat1-dev

V=0.12.1
cd $COLO/apps/mediatomb/
rm -rf mediatomb-$V install .mediatomb
if [ ! -f mediatomb-$V.tar.gz ];
then
wget http://downloads.sourceforge.net/mediatomb/mediatomb-$V.tar.gz
fi
tar zxvf mediatomb-$V.tar.gz
cd mediatomb-$V
patch -p1 < ../disable-multicast.patch
./configure --prefix=$COLO/apps/mediatomb/install/
sed -e 's/search/this->search/g' src/hash/dso_hash.h > bak.h
mv bak.h src/hash/dso_hash.h
sed -e 's/search/this->search/g' src/hash/dbo_hash.h > bak.h
mv bak.h src/hash/dbo_hash.h
sed -e 's/search/this->search/g' src/hash/dbr_hash.h > bak.h
mv bak.h src/hash/dbr_hash.h
sed -e 's/#include "nil.h"/#include <cstddef>\n#include "nil.h"/g' src/zmm/zmm.h > bak.h
mv bak.h src/zmm/zmm.h
make -j `nproc`
make install

cd $COLO/apps/mediatomb/
./generate-database
