#!/bin/bash
APP_ROOT=`pwd`
# [optional as you may have these installed]
sudo apt-get install libpcre3-dev zlib1g-dev

# download/curl/wget nginx 
wget http://nginx.org/download/nginx-1.7.9.tar.gz
tar zxvf nginx-1.7.9.tar.gz
cd nginx-1.7.9/
./configure prefix=$APP_ROOT/install
make
sudo make install

cd ..
#copy/download/curl/wget the init script
sudo wget https://raw.githubusercontent.com/JasonGiedymin/nginx-init-ubuntu/master/nginx
sudo chmod a+x nginx
sed -i "88 i NGINXPATH=$APP_ROOT/install" nginx
sed -i "84 i PATH=$PATH:$APP_ROOT/install/sbin"
service nginx status  # to poll for current status
service nginx stop    # to stop any servers if any
service nginx start   # to start the server
