#!/bin/bash

VER=0.98.6
sudo apt-get install libssl-dev
APP_ROOT=`pwd`
rm clamav-$VER install database *.conf* -rf

if [ ! -f clamav-$VER.tar.gz ]; then
wget https://distfiles.macports.org/clamav/clamav-$VER.tar.gz
fi
tar zxvf clamav-$VER.tar.gz
mkdir database

cd clamav-$VER
./configure --prefix=$APP_ROOT/install \
	--with-dbdir=$APP_ROOT/apps/clamav/install/database
make -j`nproc`
make install

cd $APP_ROOT
sed '/Example/d' $APP_ROOT/install/etc/freshclam.conf.sample > freshclam.conf
sed '/Example/d' $APP_ROOT/install/etc/clamd.conf.sample > clamd.conf
chown -R `whoami`:`whoami` $APP_ROOT/install/etc/freshclamd.conf
CURPATH=`echo $APP_ROOT`
DBPATH=$CURPATH/database
echo "DatabaseDirectory $DBPATH" >> freshclam.conf
echo "LogFile $CURPATH/server.log" >> clamd.conf
echo "DatabaseDirectory $DBPATH" >> clamd.conf
echo "TCPSocket 7000" >> clamd.conf
echo "TCPAddr 127.0.0.1" >> clamd.conf
echo "LogVerbose yes" >> clamd.conf
echo "Foreground yes" >> clamd.conf

# Prepare database
echo "Initiliazing clamav database..."
./install/bin/freshclam --config-file=./freshclam.conf

echo "Generating client conf with ports 7000 and 9000..."
./generate-client-conf lo 7000
./generate-client-conf eth0 9000

