#!/bin/bash
VER=3.6
APP_ROOT=`pwd`
rm -rf mongoose out
if [ ! -f mongoose-$VER.tgz ]; then
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mongoose/mongoose-3.6.tgz
fi
tar zxvf mongoose-$VER.tgz
cd mongoose
make linux
mv mongoose ../mg-server
